account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import (PwdResetConfirmForm, PwdResetForm, UserLoginForm)
from .views import *

# https://docs.djangoproject.com/en/3.1/topics/auth/default/
# https://ccbv.co.uk/projects/Django/3.0/django.contrib.auth.views/PasswordResetConfirmView/

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/registration/login.html',
                                                form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('register/', account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', account_activate, name='activate'),
    # Reset password
    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name="account/password_reset/password_reset_form.html",
                                              success_url='password_reset_email_confirm',
                                              email_template_name='account/password_reset/password_reset_email.html',
                                              form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset/password_reset_confirm.html',
                                                     success_url='/account/password_reset_complete/',
                                                     form_class=PwdResetConfirmForm),
         name="password_reset_confirm"),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/password_reset/reset_status.html"), name='password_reset_done'),
    path('password_reset_complete/',
         TemplateView.as_view(template_name="account/password_reset/reset_status.html"),
         name='password_reset_complete'),
    # User dashboard
    path('dashboard/', dashboard, name='dashboard'),
    path('profile/edit/', edit_details, name='edit_details'),
    path('profile/delete_user/', delete_user, name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="account/user/delete_confirm.html"),
         name='delete_confirmation'),
    path("addresses/", view_address, name="addresses"),
    path("add_address/", add_address, name="add_address"),
    path("addresses/edit/<slug:id>/", edit_address, name="edit_address"),
    path("addresses/delete/<slug:id>/", delete_address, name="delete_address"),
    path("addresses/set_default/<slug:id>/", set_default, name="set_default"),
    # Wish List
    path("wishlist", wishlist, name="wishlist"),
    path("wishlist/add_to_wishlist/<int:id>", add_to_wishlist, name="user_wishlist"),
]

basket/urls.py
from django.urls import path
from .views import *

app_name = 'basket'

urlpatterns = [
    path('', basket_summary, name='basket_summary'),
    path('checkout/', basket_checkout, name='basket_checkout'),
    path('add/', basket_add, name='basket_add'),
    path('delete/', basket_delete, name='basket_delete'),
    path('update/', basket_update, name='basket_update'),
]

garage/urls.py
from django.contrib import admin
from django.urls import path, include
from .import settings
from django.conf.urls.static import static
import debug_toolbar
from .settings import base

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('__debug__/', include(debug_toolbar.urls)),
]


if base.DEBUG:
    urlpatterns += static(base.STATIC_URL, document_root=base.STATIC_ROOT)
    urlpatterns += static(base.MEDIA_URL, document_root=base.MEDIA_ROOT)

store/urls.py
from django.urls import path
from .views import *

app_name = 'store'

urlpatterns = [
    # path('', ProductListView.as_view, name='product_list'),
    path('', all_products, name='all_products'),
    path('item/<slug:slug>/', product_detail, name='product_detail'),
    path('search/<slug:category_slug>/', category_list, name='category_list'),
    path('category/<int:category_id>/', category_list, name='category'),
    path('category/<slug:slug>/', category_list, name='category_detail'),
    path('shop/', shop, name='shop'),
]

store/models.py
from django.utils.translation import gettext_lazy as _

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

from garage.settings import base


# Create your models here.
class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True,
                            help_text='Unique value for product page URL, created from name.')
    description = models.TextField()
    is_active = models.BooleanField(default=True)
    meta_keywords = models.CharField("Meta Keywords", max_length=255,
                                     help_text='Comma-delimited set of SEO keywords for meta tag')
    meta_description = models.CharField("Meta Description", max_length=255,
                                        help_text='Content for description meta tag')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # products = models.ManyToManyField("Product", verbose_name=("Products"),
    #                                  blank=True, null=True, related_name="+")

    class Meta:
        db_table = 'categories'

    ordering = ['-created_at']
    verbose_name_plural = 'Categories'

    def __unicode__(self):
        return self.name

    # @models.permalink
    def get_absolute_url(self):
        return reverse('store:category_list', kwargs={'slug': self.slug})


class Product(models.Model):
    CONDITION = (('New', 'New Product'), ('Last', 'Last Product'))
    STATUS = (('Published', 'Published Product'), ('Draft', 'Draft Product'))
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Category',
                                 related_name='product')
    created_by = models.ForeignKey(base.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE,
                                   related_name='product_creator')
    name = models.CharField(max_length=255, unique=True)
    author = models.CharField(max_length=255, default='admin')
    slug = models.SlugField(max_length=255, unique=True,
                            help_text='Unique value for product page URL, created from name.')
    brand = models.CharField(max_length=255)
    image = models.ImageField(upload_to='images/', default='/images/car1.jpg')
    sku = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    old_price = models.DecimalField(max_digits=9, decimal_places=2,
                                    blank=True, default=0.00)
    is_active = models.BooleanField(default=True)
    is_bestseller = models.BooleanField(default=False)
    is_featured = models.BooleanField(default=False)
    in_stock = models.BooleanField(default=True)
    quantity = models.CharField(max_length=255)
    description = models.TextField(default='Description coming soon', verbose_name='Description', blank=True)
    meta_keywords = models.CharField(max_length=255,
                                     help_text='Comma-delimited set of SEO keywords for meta tag')
    meta_description = models.CharField(max_length=255,
                                        help_text='Content for description meta tag')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    color = models.CharField(max_length=30, default='white', verbose_name='Color')
    material = models.CharField(max_length=30, default='Leather', verbose_name='Material')
    condition = models.CharField(choices=CONDITION, max_length=100)
    status = models.CharField(choices=STATUS, max_length=200)
    info = models.TextField(default='Information coming soon', verbose_name='Additional Information')
    users_wishlist = models.ManyToManyField(base.AUTH_USER_MODEL, related_name='Wishlist', blank=True)
    objects = models.Manager()
    products = ProductManager()

    # categories = models.ManyToManyField("Category", verbose_name=("categories"),
    #                                     blank=True, null=True, related_name="+")
    def get_first_image(self):
        if self.images:
            try:
                return self.images.first().image.url
            except:
                return 'https://avatars.mds.yandex.net/i?id=64a306848159675833371ba4a08fa3bb655cfd8a-6971541-images-thumbs&n=13'
        else:
            return 'https://avatars.mds.yandex.net/i?id=64a306848159675833371ba4a08fa3bb655cfd8a-6971541-images-thumbs&n=13'

    class Meta:
        db_table = 'products'

    ordering = ['-created_at']
    verbose_name = 'Product'
    verbose_name_plural = 'Products'

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('store:product_detail', kwargs={'slug': self.slug})

    def sale_price(self):
        if self.old_price > self.price:
            return self.price
        else:
            return None


class ProductImage(models.Model):
    """
    The Product Image table.
    """

    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="product_image")
    image = models.ImageField(
        verbose_name=_("image"),
        help_text=_("Upload a product image"),
        upload_to="images/",
        default="images/default.png",
    )
    alt_text = models.CharField(
        verbose_name=_("Alturnative text"),
        help_text=_("Please add alturnative text"),
        max_length=255,
        null=True,
        blank=True,
    )
    is_feature = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("Product Image")
        verbose_name_plural = _("Product Images")

store/views.py
from django.shortcuts import render, get_object_or_404
from .models import *


# Create your views here.
def categories(request):
    return {'categories': Category.objects.all()}


def all_products(request):
    products = Product.products.prefetch_related("product_image").filter(is_active=True)
    return render(request, 'store/index.html', {'products': products})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request, 'store/products/detail.html', {'product': product})


def category_list(request, category_slug=None):
    category = get_object_or_404(Category, slug=category_slug)
    categories = Category.objects.all()
    products = Product.objects.filter(category__in=Category.objects.get(name=category_slug).get_descendants(include_self=True))

    context = {
        'title': f"Category: {category.title}",
        'category': category,
        'categories': categories,
        'products': products
    }
    sort_fields = request.Get.get('sort')
    if sort_fields:
        context['products'] = context['products'].order_by(*sort_fields)
    return render(request, 'store/base.html', context)


def shop(request):
    return render(request, 'store/shop/shop.html', {})

templates/store/components/_features.html
{% load static %}
<!-- ____________________Featured Section ______________________________-->
<div class="allcontain">
	<div class="feturedsection">
		<h1 class="text-center"><span class="bdots">&bullet;</span>F E A T U R E S<span class="carstxt">C A R S</span>&bullet;</h1>
	</div>
	<div class="feturedimage">
		<div class="row firstrow">
			<div class="col-lg-6 costumcol colborder1">
				<div class="row costumrow">
					<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 img1colon">
						<img src="{% static 'store/image/featurporch.jpg' %}" alt="porsche">
					</div>
					<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 txt1colon ">
						<div class="featurecontant">
							<h1>LOREM IPSUM</h1>
							<p>"Lorem ipsum dolor sit amet, consectetur ,<br>
			 						sed do eiusmod tempor incididunt </p>
			 				<h2>Price &euro;</h2>
			 				<button id="btnRM" onclick="rmtxt()">READ MORE</button>
			 				<div id="readmore">
			 						<h1>Car Name</h1>
			 						<p>"Lorem ipsum dolor sit amet, consectetur ,<br>
			 						sed do eiusmod tempor incididunt <br>"Lorem ipsum dolor sit amet, consectetur ,<br>
			 						sed do eiusmod tempor incididunt"Lorem ipsum dolor sit amet, consectetur1 ,
			 						sed do eiusmod tempor incididunt"Lorem ipsum dolor sit amet, consectetur1
			 						sed do eiusmod tempor incididunt"Lorem ipsum dolor sit amet, consectetur1<br>
			 						</p>
			 						<button id="btnRL">READ LESS</button>
			 				</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-6 costumcol colborder2">
				<div class="row costumrow">
					<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 img2colon">
						<img src="{% static 'store/image/featurporch1.jpg' %}" alt="porsche1">
					</div>
					<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 txt1colon ">
						<div class="featurecontant">
							<h1>LOREM IPSUM</h1>
							<p>"Lorem ipsum dolor sit amet, consectetur ,<br>
			 						sed do eiusmod tempor incididunt </p>
			 				<h2>Price &euro;</h2>
			 				<button id="btnRM2">READ MORE</button>
			 				<div id="readmore2">
			 						<h1>Car Name</h1>
			 						<p>"Lorem ipsum dolor sit amet, consectetur ,<br>
			 						sed do eiusmod tempor incididunt <br>"Lorem ipsum dolor sit amet, consectetur ,<br>
			 						sed do eiusmod tempor incididunt"Lorem ipsum dolor sit amet, consectetur1 ,
			 						sed do eiusmod tempor incididunt"Lorem ipsum dolor sit amet, consectetur1
			 						sed do eiusmod tempor incididunt"Lorem ipsum dolor sit amet, consectetur1<br></p>
			 						<button id="btnRL2">READ LESS</button>
			 				</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

templates/store/components/_footer.html
{% load static %}
<!-- _______________________________News Letter ____________________-->
	<div class="newslettercontent">
		<div class="leftside">
			<img src="{% static 'store/image/border.png' %}" alt="border">
			<h1>NEWSLETTER</h1>
			<p>Subscribe to the COLLECTIONCARS mailing list to <br>
				receive updates on new arrivals, special offers <br>
				and other discount information.</p>
		</div>
		<div class="rightside">
			<img class="newsimage" src="{% static 'store/image/newsletter.jpg' %}" alt="newsletter">
			<input type="text" class="form-control" id="subemail" placeholder="EMAIL">
			<button>SUBSCRIBE</button>
		</div>
	</div>
	<!-- ______________________________________________________Bottom Menu ______________________________-->
	<div class="bottommenu">
		<div class="bottomlogo">
		<span class="dotlogo">&bullet;</span><img src="{% static 'store/image/collectionlogo1.png' %}" alt="logo1"><span class="dotlogo">&bullet;;</span>
		</div>
		<ul class="nav nav-tabs bottomlinks">
			<li role="presentation" ><a href="#/" role="button">ABOUT US</a></li>
			<li role="presentation"><a href="#/">CATEGORIES</a></li>
			<li role="presentation"><a href="#/">PREORDERS</a></li>
			<li role="presentation"><a href="#/">CONTACT US</a></li>
			<li role="presentation"><a href="#/">RECEIVE OUR NEWSLETTER</a></li>
		</ul>
		<p>"Lorem ipsum dolor sit amet, consectetur,  sed do eiusmod tempor incididunt <br>
			eiusmod tempor incididunt </p>
		 <img src="{% static 'store/image/line.png' %}" alt="line"> <br>
		 <div class="bottomsocial">
		 	<a href="#"><i class="fa-brands fa-facebook"></i></a>
			<a href="#"><i class="fa-brands fa-twitter"></i></a>
			<a href="#"><i class="fa-brands fa-google-plus"></i></a>
			<a href="#"><i class="fa-brands fa-pinterest"></i></a>
		</div>
			<div class="footer">
				<div class="copyright">
				  &copy; Copy right 2016 | <a href="#">Privacy </a>| <a href="#">Policy</a>
				</div>
				<div class="atisda">
					 Designed by <a href="http://www.webdomus.net/">Web Domus Italia - Web Agency </a>
				</div>
			</div>
	</div>

templates/store/components/_header.html
{% load static %}
<style>
	::placeholder { /* Chrome, Firefox, Opera, Safari 10.1+ */
  color: white;
  opacity: 1; /* Firefox */
  text-align: center;
   font-size: 1.5rem;
}
.cart-icon {
  position: relative;
  cursor: pointer;
}
.cart-items {
  position: absolute;
  top: -12px;
  right: -10px;
  background: var(--primaryColor);
  padding: 0 3px;
  border-radius: 30%;
  color: white;
  font-size: 30px;
}
</style>
<!-- Header -->
<div class="allcontain">
	<div class="header">
			<ul class="socialicon">
				<li><a href="#"><i class="fa-brands fa-facebook"></i></a></li>
				<li><a href="#"><i class="fa-brands fa-twitter"></i></a></li>
				<li><a href="#"><i class="fa-brands fa-google-plus"></i></a></li>
				<li><a href="#"><i class="fa-brands fa-pinterest"></i></a></li>

			</ul>
			<ul class="givusacall">
				<li>Give us a call : +66666666 </li>

			</ul>
			<ul class="logreg">
				<li style="margin-right:6px;"><a href="{% url 'basket:basket_summary' %}">My cart</a><i class="fa-solid fa-cart-flatbed-suitcase"></i> </li>

				<li style="margin-right:6px;"><a href="{% url 'basket:basket_checkout' %}">Checkout </a><i class="fa-solid fa-credit-card"></i> </li>

				<li style="margin-right:6px;"><a href="{% url 'account:dashboard' %}">Account </a> <i class="fa-solid fa-address-card"></i></li>
				<li><a href="{% url 'account:login' %}">Login </a> </li>
				<li><a href="{% url 'account:register' %}"><span class="register">Register</span></a></li>
			</ul>
	</div>
	<!-- Navbar Up -->
	<nav class="topnavbar navbar-default topnav">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed toggle-costume" data-toggle="collapse" data-target="#upmenu" aria-expanded="false">
					<span class="sr-only"> Toggle navigaion</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand logo" href="/"><img src="{% static 'store/image/logo1.png' %}" alt="logo"></a>
			</div>
		</div>
		<div class="collapse navbar-collapse" id="upmenu">
			<ul class="nav navbar-nav" id="navbarontop">
				<li class="active"><a href="/">HOME</a> </li>
					<li class="active"><a href="{% url 'store:shop' %}">SHOP</a> </li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle"	data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">CATEGORIES <span class="caret"></span></a>
					<ul class="dropdown-menu dropdowncostume">

						{% for category in categories %}
						<li><a href="">{{ category.name|title }}</a></li>
{% endfor %}
					</ul>
				</li>
				<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">DEALERS <span class="caret"></span></a>
						<ul class="dropdown-menu dropdowncostume">
							<li><a href="#">1</a></li>
							<li><a href="#">2</a></li>
							<li><a href="3">3</a></li>
						</ul>
				</li>

				<li>
					<a href="contact.html">CONTACT</a>

				</li>
				<button><span class="postnewcar">POST NEW CAR</span></button>
			</ul>
		</div>
	</nav>
</div>
<!--_______________________________________ Carousel__________________________________ -->
<div class="allcontain">
	<div id="carousel-up" class="carousel slide" data-ride="carousel">
		<div class="carousel-inner " role="listbox">
			<div class="item active">
				<img src="{% static 'store/image/oldcar.jpg' %}" alt="oldcar">
				<div class="carousel-caption">
					<h2>Porsche 356</h2>
					<p>Lorem ipsum dolor sit amet, consectetur ,<br>
						sed do eiusmod tempor incididunt ut labore </p>
				</div>
			</div>
			<div class="item">
				<img src="{% static 'store/image/porche.jpg' %}" alt="porche">
				<div class="carousel-caption">
					<h2>Porche</h2>
						<p>Lorem ipsum dolor sit amet, consectetur ,<br>
						sed do eiusmod tempor incididunt ut labore </p>
				</div>
			</div>
			<div class="item">
				<img src="{% static 'store/image/benz.jpg' %}" alt="benz">
				<div class="carousel-caption">
					<h2>Car</h2>
					<p>Lorem ipsum dolor sit amet, consectetur ,<br>
						sed do eiusmod tempor incididunt ut labore </p>
				</div>
			</div>
		</div>
		<nav class="navbar navbar-default midle-nav">
			<div class="navbar-header">

				<button type="button" class="navbar-toggle collapsed textcostume btn-outline" data-toggle="collapse" data-target="#navbarmidle" aria-expanded="false">
						<h1>SEARCH TEXT</h1>

					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>


		</div>
			<div class="collapse navbar-collapse" id="navbarmidle">
				<div class="searchtxt">
					<h1>SEARCH TEXT</h1>

				</div>
				<button class="searchbutton"><span class="glyphicon glyphicon-search "></span></button>
				<form class="navbar-form navbar-left searchformmargin" role="search">
					<div class="form-group">
						<input type="text" class="form-control searchform" placeholder="Enter Keyword">
					</div>
				</form>
				<ul class="nav navbar-nav navbarborder">
					<li class="li-category">
						<a class="btn  dropdown-toggle btn-costume"  id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Category<span class="glyphicon glyphicon-chevron-down downicon"></span></a>
						<ul class="dropdown-menu" id="mydd">
							<li><a href="#">Epic</a></li>
							<li><a href="#">Old</a></li>
							<li><a href="#">New</a></li>
						</ul>
					</li>
					<li class="li-minyear"><a class="btn  dropdown-toggle btn-costume"  id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Min Year <span class="glyphicon glyphicon-chevron-down downicon"></span></a>
						<ul class="dropdown-menu" id="mydd2">
							<li><a href="#">1</a></li>
							<li><a href="#">2</a></li>
							<li><a href="#">3</a></li>
						</ul>
					</li>
					<li class="li-maxyear"><a class="btn dropdown-toggle btn-costume"  id="dropdownMenu3" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Max Year <span class="glyphicon glyphicon-chevron-down downicon"></span></a>
						<ul class="dropdown-menu" id="mydd3">
							<li><a href="#">1900</a></li>
							<li><a href="#">2000</a></li>
							<li><a href="#">2016</a></li>
						</ul>
					</li>
					<li class="li-slideprice">
						<p>
							<input class="priceslider" type="text" id="amount" readonly="readonly" placeholder="Price" style="border:1px solid white; height:42px;">
						</p>
						 <li class="cart-icon"><a href="{% url 'basket:basket_summary' %}">
					{% with total_qty=basket|length %}
					<div id="basket-qty" class="cart-items">
					{% if total_qty > 0 %}
				   {{ total_qty }}
					{% else %}
					0
					{% endif %}
					</div>
					{% endwith %}
					<i class="fas fa-cart-plus"></i></a> </li>
							<div id="slider-range"></div>

					</li>

				</ul>

			</div>
		</nav>
	</div>
</div>

templates/store/components/_links.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'store/source/bootstrap-3.3.6-dist/css/bootstrap.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'store/source/font-awesome-4.5.0/css/font-awesome.css' %}">
	<link rel="stylesheet" type="text/css" href="[% static 'store/style/slider.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static  'store/style/mystyle.css' %}">
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

templates/store/components/_scripts.html
{% load static %}
<script type="text/javascript" src="{% static 'store/source/bootstrap-3.3.6-dist/js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'store/source/js/isotope.js' %}"></script>
<script type="text/javascript" src="{% static 'store/source/js/myscript.js' %}"></script>
<script type="text/javascript" src="{% static 'store/source/bootstrap-3.3.6-dist/js/jquery.1.11.js' %}"></script>
<script type="text/javascript" src="{% static 'store/source/bootstrap-3.3.6-dist/js/bootstrap.js' %}"></script>
<script>
    $(document).on('click', '#delete-button',  function(e){
    e.preventDefault();
    $.ajax({
    type: 'POST',
    url: '{% url 'basket:basket_delete' %},
    data: {
    productid: $(this).data('index'),
    csrfmiddlewaretoken: '{{csrf_token}}',
    action: 'post',
    },
    success: function(json){
    alert('ok');
    },
    error: function(xhr, errmsg, err){
    alert('error');
    }
    });
    });

     $(document).on('click', '#add-button',  function(e){
    e.preventDefault();
    $.ajax({
    type: 'POST',
    url: '{% url 'basket:basket_add' %},
    data: {
    productid: $('#add-button').val(),
    productqty: $('#quantity-select option:selected').text(),
    csrfmiddlewaretoken: '{{csrf_token}}',
    action: 'post',
    },
    success: function(json){
    document.getElementById('basket-qty').innerHTML = json.basket_qty;
    },
    error: function(xhr, errmsg, err){
    alert('error');
    }
    });
    });

</script>